---
server:
  port: 8082
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    #url: jdbc:h2:file:./demo
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
...